[package]
name = "imageflow_helpers"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
workspace = "../"

[dependencies]
libc = "0.2"

# time
time = "*"
chrono =  "0.4"

# serialization
serde = "*"
serde_json = "*"
serde_derive = "*"
rustc-serialize = "*"

#lazy static
lazy_static = "0.2"

# fast hashes, crypto hashs
twox-hash = "1"
fnv = "*"
blake2-rfc = "*"
sha2 = "*"

uuid = { version = "*", features= ["v4", "v5"]}

lockless = "*"
smallvec = "*"
# regex
regex = "*"

num = "*"

base64 = "*"
mockito = "*"
zip = { version = "0.2", default-features = false }


app_dirs = "^1.1.1"
chashmap = "*"
parking_lot = {version = "0.4", features = ["nightly"]}


unicase = "2"
# HTTPS is a little bit of a nightmare

error-chain = "*"

hyper = "*"
reqwest = "*"
hyper-native-tls = "*"

backtrace = "0.3.2"


[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies]
openssl = "*"
hyper-openssl = "*"
